/** Central API path constants — update here when backend renames routes */

export const API = {
  auth: {
    login: "/api/Authentication/login",
    refresh: "/api/Authentication/refresh",
    logout: "/api/Authentication/logout",
    changePassword: "/api/Authentication/ChangePassword",
  },
  access: {
    createUser: "/api/Access/CreateUser",
    resetPassword: "/api/Access/ResetPasswordForUser",
    addUserToRoles: "/api/Access/AddUserToRoles",
    removeFromSingleRole: "/api/Access/RemoveUserFromSingleRole",
    removeFromMultipleRoles: "/api/Access/RemoveUserFromMultipleRoles",
    getUsers: "/api/Access/GetUsersWithSearch",
    getSingleUser: "/api/Access/GetSingleUser",
    updateUser: "/api/Access/UpdateUser",
    filter: "/api/Access/filter",
    deleteUser: "/api/Access/DeleteUser",
    deactivate: "/api/Access/DeactivateUser",
    reactivate: "/api/Access/ReActivateUser",
  },
  roles: {
    create: "/api/Roles/role/create-role",
    getAll: "/api/Roles/roles/getall-roles",
    setPermission: "/api/Roles/permissions/set-permission",
    permissionsForRole: (roleName: string) =>
      `/api/Roles/permissions/for-roles/${encodeURIComponent(roleName)}`,
    allWithPermissions: "/api/Roles/allroles-with-permissions",
    addWithPermissions: "/api/Roles/permissions/AddRolesWithPermissions",
    getById: "/api/Roles/GetRoleByID",
    updateWithPermissions: "/api/Roles/UpdateRoleAndPermissions",
  },
  residents: {
    createWithUser: "/api/Residents/CreateResidentWithUserAcct",
    create: "/api/Residents/CreateResident",
    update: "/api/Residents/UpdateResidentInformation",
    getById: (id: number | string) => `/api/Residents/GetResidentById/${id}`,
    search: "/api/Residents/SearchResidents",
    delete: (id: number | string) => `/api/Residents/DeleteResident/${id}`,
  },
  staff: {
    createWithAccount: "/api/Staff/CreateAndRegisterNewStaffAccount",
    create: "/api/Staff/CreateNewStaff",
    getByCriteria: "/api/Staff/GetStaffByCriteria",
    getById: (id: number | string) => `/api/Staff/GetStaffById${id}`,
    update: "/api/Staff/UpdateStaff",
    delete: (id: number | string) => `/api/Staff/DeleteStaff${id}`,
    departments: "/api/Staff/GetDepartmentList",
  },
  visitors: {
    create: "/api/Visitors/CreateNew",
    update: "/api/Visitors/Update",
    getById: "/api/Visitors/GetById",
    getByCriteria: "/api/Visitors/GetByCriteria",
    checkIn: "/api/Visitors/CheckVistorIn", // API typo
    checkOut: "/api/Visitors/CheckVisitorOut",
    delete: (id: number | string) => `/api/Visitors/DeleteVisitor/${id}`,
  },
  serviceRequests: {
    categories: "/api/ServiceRequests/categories",
    create: "/api/ServiceRequests/CreateServiceRequest",
    update: "/api/ServiceRequests/UpdateServiceRequest",
    assign: "/api/ServiceRequests/AssignServiceRequest",
    resolve: "/api/ServiceRequests/ResolveServiceRequest",
    close: "/api/ServiceRequests/CloseServiceRequest",
    reopen: "/api/ServiceRequests/ReopenServiceRequest",
    getById: "/api/ServiceRequests/GetServiceRequestById",
    search: "/api/ServiceRequests/SearchServiceRequests",
    open: "/api/ServiceRequests/GetOpenServiceRequests",
    summary: "/api/ServiceRequests/GetServiceRequestDashboardSummary",
    delete: "/api/ServiceRequests/DeleteServiceRequest",
  },
  collections: {
    create: "/api/Collections",
    recordPayment: "/api/Collections/payment",
    search: "/api/Collections/SearchCollections",
    outstanding: "/api/Collections/GetOutstandingCollections",
    overdue: "/api/Collections/GetOverdueCollections",
    paid: "/api/Collections/GetPaidCollections",
    delete: "/api/Collections/DeleteCollection",
  },
  collectionConfig: {
    create: "/api/CollectionsConfiguration/CreateCollectionConfiguration",
    update: "/api/CollectionsConfiguration/UpdateCollectionConfiguration",
    search: "/api/CollectionsConfiguration/SearchCollectionConfigurations",
    active: "/api/CollectionsConfiguration/GetActiveCollectionConfigurations",
    delete: "/api/CollectionsConfiguration/DeleteCollectionConfiguration",
    getById: "/api/CollectionsConfiguration/GetCollectionConfigurationById",
  },
  collectionPayments: {
    create: "/api/CollectionPayments/CreateCollectionPayment",
    search: "/api/CollectionPayments/SearchCollectionPayments",
    summary: "/api/CollectionPayments/DashboardSummary",
  },
  announcements: {
    create: "/api/Announcements/CreateAnnouncement",
    update: "/api/Announcements/UpdateAnnouncement",
    publish: "/api/Announcements/PublishAnnouncement",
    unpublish: "/api/Announcements/UnpublishAnnouncement",
    search: "/api/Announcements/SearchAnnouncements",
    published: "/api/Announcements/GetPublishedAnnouncements",
    draft: "/api/Announcements/GetDraftAnnouncements",
    summary: "/api/Announcements/AnnouncementDashboardSummary",
    delete: "/api/Announcements/DeleteAnnouncement",
  },
  issues: {
    create: "/api/Issues/CreateNew",
    update: "/api/Issues/Update",
    getByCriteria: "/api/Issues/GetByCritera", // API typo
    delete: "/api/Issues/Delete",
  },
  marketplace: {
    create: "/api/MarketplaceItems/CreateMarketplaceItem",
    approve: "/api/MarketplaceItems/ApproveMarketplaceItem",
    reject: "/api/MarketplaceItems/RejectMarketplaceItem",
    search: "/api/MarketplaceItems/SearchMarketplaceItems",
    pending: "/api/MarketplaceItems/GetMarketplaceItemsPendingApproval",
    approved: "/api/MarketplaceItems/GetApprovedMarketplaceItems",
    summary: "/api/MarketplaceItems/GetMarketplaceDashboardSummary",
    categories: "/api/MarketplaceCategories/GetActiveMarketplaceCategories",
  },
  vehicles: {
    search: "/api/ResidentVehicles/SearchResidentVehicles",
    create: "/api/ResidentVehicles/CreateResidentVehicle",
    update: "/api/ResidentVehicles/UpdateResidentVehicle",
    verify: "/api/ResidentVehicles/VerifyVehicleAccess",
    logsSearch: "/api/VehicleAccessLogs/SearchLog",
  },
} as const;
