/** Central API path constants — update here when backend renames routes.
 *  Backend typos are intentional and mirrored as-is.
 */

export const API = {
  auth: {
    login: "/api/Authentication/login",
    refresh: "/api/Authentication/refresh",
    logout: "/api/Authentication/logout",
    changePassword: "/api/Authentication/ChangePassword",
  },
  access: {
    createUser: "/api/Access/CreateUser",
    resetPassword: "/api/Access/ResetPasswordForUser",
    addUserToRoles: "/api/Access/AddUserToRoles",
    removeFromSingleRole: "/api/Access/RemoveUserFromSingleRole",
    removeFromMultipleRoles: "/api/Access/RemoveUserFromMultipleRoles",
    getUsers: "/api/Access/GetUsersWithSearch",
    getSingleUser: "/api/Access/GetSingleUser",
    updateUser: "/api/Access/UpdateUser",
    filter: "/api/Access/filter",
    deleteUser: "/api/Access/DeleteUser",
    deactivate: "/api/Access/DeactivateUser",
    reactivate: "/api/Access/ReActivateUser",
  },
  roles: {
    create: "/api/Roles/role/create-role",
    getAll: "/api/Roles/roles/getall-roles",
    setPermission: "/api/Roles/permissions/set-permission",
    permissionsForRole: (roleName: string) =>
      `/api/Roles/permissions/for-roles/${encodeURIComponent(roleName)}`,
    allWithPermissions: "/api/Roles/allroles-with-permissions",
    addWithPermissions: "/api/Roles/permissions/AddRolesWithPermissions",
    getById: "/api/Roles/GetRoleByID",
    updateWithPermissions: "/api/Roles/UpdateRoleAndPermissions",
  },
  residents: {
    createWithUser: "/api/Residents/CreateResidentWithUserAcct",
    create: "/api/Residents/CreateResident",
    update: "/api/Residents/UpdateResidentInformation",
    getById: (id: number | string) => `/api/Residents/GetResidentById/${id}`,
    search: "/api/Residents/SearchResidents",
    delete: (id: number | string) => `/api/Residents/DeleteResident/${id}`,
  },
  staff: {
    createWithAccount: "/api/Staff/CreateAndRegisterNewStaffAccount",
    create: "/api/Staff/CreateNewStaff",
    getByCriteria: "/api/Staff/GetStaffByCriteria",
    getById: (id: number | string) => `/api/Staff/GetStaffById${id}`,
    update: "/api/Staff/UpdateStaff",
    delete: (id: number | string) => `/api/Staff/DeleteStaff${id}`,
    departments: "/api/Staff/GetDepartmentList",
  },
  visitors: {
    create: "/api/Visitors/CreateNew",
    update: "/api/Visitors/Update",
    getById: "/api/Visitors/GetById",
    getByCriteria: "/api/Visitors/GetByCriteria",
    getByVerificationCode: "/api/Visitors/GetByVerificationCode",
    delete: (id: number | string) => `/api/Visitors/DeleteVisitor/${id}`,
    verify: (code: string) => `/api/Visitors/VerifyVisitor/${encodeURIComponent(code)}`,
    byResident: "/api/Visitors/GetVisitorsByResident",
    active: "/api/Visitors/GetActiveVisitors",
    pending: "/api/Visitors/GetPendingVisitors",
    checkIn: "/api/Visitors/CheckVistorIn",
    checkOut: "/api/Visitors/CheckVisitorOut",
    logById: (id: number | string) => `/api/Visitors/GetVisitorLogById/${id}`,
    logsByCriteria: "/api/Visitors/GetVisitorsLogByCriteria",
    deleteLog: "/api/Visitors/DeleteVisitorLog",
    activeVisits: "/api/Visitors/GetActiveVisits",
    checkedOut: "/api/Visitors/CheckedOutVisitors",
    logsByVisitor: "/api/Visitors/GetVisitorLogsByVisitor",
    logsByOfficer: (id: number | string) =>
      `/api/Visitors/VisitorLogsBySecurityOfficer/${id}`,
    searchLogsByCode: (code: string) =>
      `/api/Visitors/SearchLogsByVerificationCode/${encodeURIComponent(code)}`,
    activeVisitByCode: (code: string) =>
      `/api/Visitors/ActiveVisitByVerificationCode/${encodeURIComponent(code)}`,
  },
  serviceRequests: {
    categories: "/api/ServiceRequests/categories",
    create: "/api/ServiceRequests/CreateServiceRequest",
    update: "/api/ServiceRequests/UpdateServiceRequest",
    assign: "/api/ServiceRequests/AssignServiceRequest",
    resolve: "/api/ServiceRequests/ResolveServiceRequest",
    close: "/api/ServiceRequests/CloseServiceRequest",
    reopen: "/api/ServiceRequests/ReopenServiceRequest",
    getById: "/api/ServiceRequests/GetServiceRequestById",
    search: "/api/ServiceRequests/SearchServiceRequests",
    open: "/api/ServiceRequests/GetOpenServiceRequests",
    active: "/api/ServiceRequests/GetActiveServiceRequests",
    critical: "/api/ServiceRequests/GetCriticalServiceRequests",
    byResident: "/api/ServiceRequests/GetServiceRequestsByResident",
    summary: "/api/ServiceRequests/GetServiceRequestDashboardSummary",
    delete: "/api/ServiceRequests/DeleteServiceRequest",
  },
  collections: {
    create: "/api/Collections",
    recordPayment: "/api/Collections/payment",
    getById: "/api/Collections/GetCollectionById",
    search: "/api/Collections/SearchCollections",
    delete: "/api/Collections/DeleteCollection",
    byResident: "/api/Collections/GetCollectionsByResident",
    byStatus: "/api/Collections/GetCollectionsByStatus",
    outstanding: "/api/Collections/GetOutstandingCollections",
    paid: "/api/Collections/GetPaidCollections",
    overdue: "/api/Collections/GetOverdueCollections",
    partiallyPaid: "/api/Collections/GetPartiallyPaidCollections",
    byConfiguration: "/api/Collections/GetCollectionsByConfiguration",
    paymentDetailForResident: "/api/Collections/GetPaymentDetailForResident",
  },
  collectionConfig: {
    create: "/api/CollectionsConfiguration/CreateCollectionConfiguration",
    update: "/api/CollectionsConfiguration/UpdateCollectionConfiguration",
    search: "/api/CollectionsConfiguration/SearchCollectionConfigurations",
    active: "/api/CollectionsConfiguration/GetActiveCollectionConfigurations",
    activeMandatory:
      "/api/CollectionsConfiguration/GetActiveMandatoryCollectionConfigurations",
    mandatory: "/api/CollectionsConfiguration/GetMandatoryCollectionConfigurations",
    monthly: "/api/CollectionsConfiguration/GetMonthlyCollectionConfigurations",
    yearly: "/api/CollectionsConfiguration/GetYearlyCollectionConfigurations",
    byFrequency: "/api/CollectionsConfiguration/GetCollectionConfigurationsByFrequency",
    delete: "/api/CollectionsConfiguration/DeleteCollectionConfiguration",
    getById: "/api/CollectionsConfiguration/GetCollectionConfigurationById",
  },
  collectionPayments: {
    create: "/api/CollectionPayments/CreateCollectionPayment",
    getById: (id: number | string) =>
      `/api/CollectionPayments/GetCollectionPaymentById${id}`,
    search: "/api/CollectionPayments/SearchCollectionPayments",
    delete: (id: number | string) =>
      `/api/CollectionPayments/DeleteCollectionPayment${id}`,
    byCollectionId: "/api/CollectionPayments/GetPaymentsByCollectionId",
    byPaymentReference: "/api/CollectionPayments/GetPaymentByPaymentReference",
    byChannel: "/api/CollectionPayments/GetPaymentsByPaymentChannel",
    byReceipt: "/api/CollectionPayments/GetPaymentsByReceiptNumber",
    byGateway: "/api/CollectionPayments/GetPaymentsByGatewayReference",
    summary: "/api/CollectionPayments/DashboardSummary",
    summaryFiltered: "/api/CollectionPayments/SummaryFiltered",
    bulk: "/api/CollectionPayments/SubmitBulkPaymentForResident",
  },
  announcements: {
    create: "/api/Announcements/CreateAnnouncement",
    update: "/api/Announcements/UpdateAnnouncement",
    publish: "/api/Announcements/PublishAnnouncement",
    unpublish: "/api/Announcements/UnpublishAnnouncement",
    getById: "/api/Announcements/GetAnnouncementById",
    search: "/api/Announcements/SearchAnnouncements",
    published: "/api/Announcements/GetPublishedAnnouncements",
    active: "/api/Announcements/GetActiveAnnouncements",
    draft: "/api/Announcements/GetDraftAnnouncements",
    critical: "/api/Announcements/GetCriticalAnnouncements",
    requiringAck: "/api/Announcements/AnnRequiringAcknowledgement",
    summary: "/api/Announcements/AnnouncementDashboardSummary",
    delete: "/api/Announcements/DeleteAnnouncement",
  },
  issues: {
    create: "/api/Issues/CreateNew",
    update: "/api/Issues/Update",
    getById: "/api/Issues/GetById",
    getByCriteria: "/api/Issues/GetByCritera",
    delete: "/api/Issues/Delete",
  },
  marketplace: {
    create: "/api/MarketplaceItems/CreateMarketplaceItem",
    update: "/api/MarketplaceItems/UpdateMarketplaceItem",
    approve: "/api/MarketplaceItems/ApproveMarketplaceItem",
    reject: "/api/MarketplaceItems/RejectMarketplaceItem",
    delete: "/api/MarketplaceItems/DeleteMarketplaceItem",
    search: "/api/MarketplaceItems/SearchMarketplaceItems",
    pending: "/api/MarketplaceItems/GetMarketplaceItemsPendingApproval",
    approved: "/api/MarketplaceItems/GetApprovedMarketplaceItems",
    rejected: "/api/MarketplaceItems/GetRejectedMarketplaceItems",
    featured: "/api/MarketplaceItems/GetFeaturedMarketplaceItems",
    byCategory: "/api/MarketplaceItems/GetMarketplaceItemsByCategory",
    byResident: "/api/MarketplaceItems/GetMarketplaceItemsByResident",
    getById: "/api/MarketplaceItems/GetMarketplaceItemById",
    detailsWithGallery: "/api/MarketplaceItems/GetMarketplaceItemDetailsWithGallery",
    summary: "/api/MarketplaceItems/GetMarketplaceDashboardSummary",
    incrementViews: "/api/MarketplaceItems/IncrementMarketplaceItemViewCount",
  },
  marketplaceCategories: {
    create: "/api/MarketplaceCategories/CreateMarketplaceCategory",
    update: "/api/MarketplaceCategories/UpdateMarketplaceCategory",
    delete: (id: number | string) =>
      `/api/MarketplaceCategories/DeleteMarketplaceCategory/${id}`,
    active: "/api/MarketplaceCategories/GetActiveMarketplaceCategories",
    inactive: "/api/MarketplaceCategories/GetInactiveMarketplaceCategories",
    lookup: "/api/MarketplaceCategories/GetCategoryLookup",
    ordered: "/api/MarketplaceCategories/GetOrderedMarketplaceCategories",
    search: "/api/MarketplaceCategories/SearchCategories",
    getById: "/api/MarketplaceCategories/GetMarketplaceCategoryById",
    getByCode: "/api/MarketplaceCategories/GetMarketplaceCategoryByCategoryCode",
  },
  marketplaceImages: {
    create: "/api/MarketplaceItemImages/CreateMarketplaceItemImage",
    update: "/api/MarketplaceItemImages/UpdateMarketplaceItemImage",
    delete: "/api/MarketplaceItemImages/DeleteMarketplaceItemImage",
    byItem: "/api/MarketplaceItemImages/GetImagesByMarketplaceItem",
    gallery: "/api/MarketplaceItemImages/GetMarketplaceItemGallery",
    getById: "/api/MarketplaceItemImages/GetMarketplaceItemImageById",
    primary: "/api/MarketplaceItemImages/GetPrimaryMarketplaceItemImage",
    search: "/api/MarketplaceItemImages/SearchMarketplaceItemImages",
    setPrimary: "/api/MarketplaceItemImages/SetPrimaryMarketplaceItemImage",
  },
  vehicles: {
    create: "/api/ResidentVehicles/CreateResidentVehicle",
    update: "/api/ResidentVehicles/UpdateResidentVehicle",
    delete: "/api/ResidentVehicles/DeleteResidentVehicle",
    search: "/api/ResidentVehicles/SearchResidentVehicles",
    getById: "/api/ResidentVehicles/GetResidentVehicleById",
    byResident: "/api/ResidentVehicles/GetVehiclesByResident",
    active: "/api/ResidentVehicles/GetActiveVehicles",
    primary: "/api/ResidentVehicles/GetPrimaryVehicles",
    summary: "/api/ResidentVehicles/GetVehicleDashboardSummary",
    verify: "/api/ResidentVehicles/VerifyVehicleAccess",
  },
  vehicleLogs: {
    create: "/api/VehicleAccessLogs/CreateVehicleAccessLog",
    update: (id: number | string) =>
      `/api/VehicleAccessLogs/UpdateVehicleAccessLog/${id}`,
    getById: (id: number | string) =>
      `/api/VehicleAccessLogs/GetVehicleAccessLogById/${id}`,
    search: "/api/VehicleAccessLogs/SearchLog",
    verifyAccess: "/api/VehicleAccessLogs/VerifyAccess",
    history: "/api/VehicleAccessLogs/history",
    entry: "/api/VehicleAccessLogs/GetEntryLogs",
    exit: "/api/VehicleAccessLogs/GetExitLogs",
    granted: "/api/VehicleAccessLogs/GetGrantedAccessLogs",
    denied: "/api/VehicleAccessLogs/GetVehiclesDeniedAccess",
    summary: "/api/VehicleAccessLogs/GetVehicleAccessDashboardSummary",
    delete: "/api/VehicleAccessLogs/DeleteVehicleAccessLog",
  },
  pushNotifications: {
    send: "/api/PushNotifications/SendNotifications",
    unread: "/api/PushNotifications/GetAllUnreadNotifications",
    getSingle: "/api/PushNotifications/GetSingleNotification",
    markRead: "/api/PushNotifications/MarkNotificationAsRead",
    markUnread: "/api/PushNotifications/MarkNotificationUnread",
    markAllRead: "/api/PushNotifications/MarkAllNotificationAsRead",
    clearAll: "/api/PushNotifications/ClearAllNotifications",
  },
  meetingSummary: {
    create: "/api/MeetingSummary/CreateMeetingSummar",
    update: "/api/MeetingSummary/UpdateMeetingSummary",
    delete: (id: number | string) =>
      `/api/MeetingSummary/DeleteMeetingSummary/${id}`,
    list: "/api/MeetingSummary/GetMeetingSmmarylist",
  },
} as const;
